### ISSUE TITLE
Python2 import error

### ISSUE THREAD

**Issue by andersx** [azag0/pyberny#1]
Hi, import works fine under Python3, but I get the following error from Python2
```
>>> import berny
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andersx/.local/lib/python2.7/site-packages/berny/__init__.py", line 1, in <module>
    from .berny import Berny, Logger
  File "/home/andersx/.local/lib/python2.7/site-packages/berny/berny.py", line 22
    def __call__(self, *lines, level=0):
                                   ^
SyntaxError: invalid syntax
```
/Anders

**Comment by andersx** [comment]
Thanks, that was quick! :)

**Comment by azag0** [comment]
Hi, thanks. Easy to forget these things do not work in Python 2.

Btw, here's a Jupyter [notebook](http://nbviewer.jupyter.org/urls/pub.hermann.in/e7/422a6166/grad.ipynb) using [pyscf](https://github.com/sunqm/pyscf) to optimize a methane molecule. Long-term, I'd like to have some robust testing framework, but there's nothing like that for now.

Also, I'm sure you'll encounter problems very soon. Please, think of it more as a work-in-progress.
