### ISSUE TITLE
 Anaconda Cloud deployments?

### ISSUE THREAD

**Issue by mjw99** [azag0/pyberny#16]
With the advent of releases in this project, would it be be possible to have deployment to the Anaconda Cloud  (https://anaconda.org/) ?

**Comment by azag0** [comment]
I don't plan to. I don't use conda packages myself, and pyberny being pure python, I don't see advantage of conda over pip.

But if you create a pull request with all the necessary conda recipe files, I'll be happy to publish minor versions on the Anaconda Cloud.

**Comment by mjw99** [comment]
Thanks Jan, I will brush up on how to generate conda recipes.

**Comment by mjw99** [comment]
I think this can be closed for the moment, I current have a solution with pip. Thank you for looking into this.
