### ISSUE TITLE
Missing test framework

### ISSUE THREAD

**Issue by azag0** [azag0/pyberny#2]
Having good tests will be crucial for a geometry optimizer, because it's very easy to unconsciously break existing behavior.

For that, there should be a fast, lightweight method (force field?) for getting energies and gradients, that has a Python API and works for both molecules and crystals.

**Comment by isayev** [comment]
Hey, @azag0 do you have a working example with MOPAC or any QM code? I am trying to use pyberny with my [ML empirical potential](https://github.com/isayev/ASE_ANI), but could not converge optimization for any molecule. Thanks.

BTW, Down the road ANI-1 could be a choice to run fast tests, because you could also do reactions with it.

**Comment by sunqm** [comment]
Seems working alright with pyscf
https://github.com/sunqm/pyscf/blob/master/pyscf/geomopt/berny_solver.py#L60

**Comment by azag0** [comment]
I've added a pytest test framework in 5033ea4. At the moment, it contains a single basic test using a Mopac2016 driver. There is no documentation, let's see first if it's the right approach.

**Comment by azag0** [comment]
@isayev You can see an example with Mopac2016 [here](https://github.com/azag0/pyberny/blob/master/tests/test_berny.py).

**Comment by isayev** [comment]
Thanks a lot, @azag0 ! Those two solver examples are very useful 👍

**Comment by isayev** [comment]
When I use your default mopac example, [Aniline](https://github.com/nutjunkie/IQmol/blob/master/share/fragments/Molecules/Aromatics/Aniline.xyz) (and most of other complex molecules I tried) diverge with MOPAC2016:

> 1 Energy: -37.3916665135
> 2 Energy: -37.3919700706
> 3 Energy: -37.3931100633
> 4 Energy: -37.3933052071
> 5 Energy: -37.3933573925
> 6 Energy: -37.3936675646
> 7 Energy: -37.3938858611
> 8 Energy: -37.3934018603
> 9 Energy: -36.6168003763
> 10 Energy: -36.7497072843
> 11 Energy: -37.1491567655
> 12 Energy: -36.8690647429
> 13 Energy: -36.6806972992
> 14 Energy: -36.5497679222
> 15 Energy: -36.4247240975
> 16 Energy: -36.0447673158
> 17 Energy: -33.6421988409
> 18 Energy: -33.921989144
> 19 Energy: -33.9627506826
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-18-a54670fd8e49> in <module>()
>       1 solver = MopacSolver(cmd='/opt/mopac/MOPAC2016.exe')
> ----> 2 final = optimize(solver, ethanol,  steprms=0.01, stepmax=0.05)
> 
> /home/olexandr/anaconda3/lib/python3.5/site-packages/berny-0.1-py3.5.egg/berny/berny.py in optimize(solver, geom, **kwargs)
>     117     optimizer = Berny(geom, log=logger, **kwargs)
>     118     for geom in optimizer:
> --> 119         energy, gradients = solver.send(list(geom))
>     120         optimizer.send((energy, gradients))
>     121     return geom
> 
> /home/olexandr/anaconda3/lib/python3.5/site-packages/berny-0.1-py3.5.egg/berny/solvers.py in MopacSolver(cmd, method)
>      25                 gradients = [
>      26                     [float(next(f).split()[6])/kcal*angstrom for _ in range(3)]
> ---> 27                     for _ in range(len(atoms))
>      28                 ]
>      29 
> 
> /home/olexandr/anaconda3/lib/python3.5/site-packages/berny-0.1-py3.5.egg/berny/solvers.py in <listcomp>(.0)
>      25                 gradients = [
>      26                     [float(next(f).split()[6])/kcal*angstrom for _ in range(3)]
> ---> 27                     for _ in range(len(atoms))
>      28                 ]
>      29 
> 
> /home/olexandr/anaconda3/lib/python3.5/site-packages/berny-0.1-py3.5.egg/berny/solvers.py in <listcomp>(.0)
>      24                 next(f)
>      25                 gradients = [
> ---> 26                     [float(next(f).split()[6])/kcal*angstrom for _ in range(3)]
>      27                     for _ in range(len(atoms))
>      28                 ]
> 
> ValueError: could not convert string to float: 'KCAL/ANGSTROM'
