### ISSUE TITLE
what is wrong with providing setup.py?

### ISSUE THREAD

**Issue by flokno** [azag0/pyberny#25]
as the title says

**Comment by azag0** [comment]
Nothing, but it isn't needed. Pyberny uses [Poetry](https://poetry.eustace.io) for packaging and dependency management.

**Comment by azag0** [comment]
What do you need setup.py for?

**Comment by flokno** [comment]
I just wanted to install via `python setup.py instal ...` and could'nt.

Maybe I should read up on poetry then!

**Comment by azag0** [comment]
You can install a released version from pypi with pip: pip install pyberny. You can directly use the master branch without installing by having it in sys.path. Or you can use poetry and add the pyberny package as a path or git dependency: https://poetry.eustace.io/docs/cli/#add

**Comment by flokno** [comment]
ok thanks for clarification
