### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by litman90** [azag0/pyberny#31]
Hi, 
I report this here rather than sending a personal email since several people could be interested to comment.
Basically, the documentation provided is quite general. It would desirable to have a more specific explanation of, at least, which features this project contains. The documentation only describes how the internal coordinates are computed and sketches how to go back to cartesian ones. Something like, which actually optimization algorithms are already implemented or if any constraint can be applied would help to any potential user (like me) to know if he/she is interested in the project and if it is worth it to spend some time navigating through the code or not.

I guess that it shouldn't be too difficult or time-consuming, but it would be quite useful.
Regards,
Yair

**Comment by litman90** [comment]
Those 3 lines are adding valuable information.
I would also suggest differentiating, if possible, which algorithms/implementations are the standard textbook ones, which are less standard but still have a reference that could be cited and finally, which are original in this library. I think that together with the lines you wrote above, it would be sufficient as a project description for any potential new user. Then going through the code to understand the details will be up to the user.

**Comment by azag0** [comment]
I've updated the readme and the [algorithm](https://janhermann.cz/pyberny/algorithm.html) section of the docs. Let me know if you find it sufficient now.

**Comment by litman90** [comment]
Yes, now it is pretty clear.
Thanks
